Fix web: exception on bad requests
Currently bad requests to the web endpoint will throw exceptions like (making it difficult to play with):

```
[2021-01-20 18:02:40,637] [ERROR@aiohttp.server] Unhandled exception
Traceback (most recent call last):
  File "/path/matrix/mautrix-facebook/mautrix_facebook/web/public.py", line 92, in check_token
    user_id = request.query["user_id"]
KeyError: 'user_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.virtualenvs/bridge-fb/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/root/.virtualenvs/bridge-fb/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/path/matrix/mautrix-facebook/mautrix_facebook/web/public.py", line 105, in status
    user = await self.check_token(request)
  File "/path/matrix/mautrix-facebook/mautrix_facebook/web/public.py", line 94, in check_token
    raise web.HTTPBadRequest(body='{"error": "Missing user_id query param"}',
aiohttp.web_exceptions.HTTPBadRequest: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/.virtualenvs/bridge-fb/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 485, in start
    resp, reset = await task
  File "/path/.virtualenvs/bridge-fb/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 427, in _handle_request
    status=exc.status, reason=exc.reason, text=exc.text, headers=exc.headers
  File "/path/.virtualenvs/bridge-fb/lib/python3.8/site-packages/aiohttp/web_response.py", line 650, in text
    return self._body.decode(self.charset or "utf-8")
AttributeError: 'StringPayload' object has no attribute 'decode'
```